name: rinha-backend-2026-elixir

services:
  lb:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - sock:/run/sock
    ports:
      - "9999:9999"
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: 20MB

  api01:
    image: acauhi/rinha-2026-elixir@sha256:1e3748e243f6855e176b4e3fc46df6a10a796ee8d3a666469a254faa0e583f7c
    environment:
      SOCKET_PATH: /run/sock/api01.sock
      INDEX_DIR: /app/index
      CANDIDATES_TARGET: "1200"
      CANDIDATES_HARD_CAP: "2000"
      NPROBE_PRIMARY: "240"
      NPROBE_SECOND_PASS: "240"
      BORDERLINE_SECOND_PASS_ENABLED: "0"
      BORDERLINE_HITS_MIN: "2"
      BORDERLINE_HITS_MAX: "3"
      RINHA_RESOURCES_DIR: /app/resources
      ERL_AFLAGS: "+S 1:1 +A 1 +sbwt none +sbwtdcpu none +sbwtdio none"
    volumes:
      - sock:/run/sock
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: 165MB

  api02:
    image: acauhi/rinha-2026-elixir@sha256:1e3748e243f6855e176b4e3fc46df6a10a796ee8d3a666469a254faa0e583f7c
    environment:
      SOCKET_PATH: /run/sock/api02.sock
      INDEX_DIR: /app/index
      CANDIDATES_TARGET: "1200"
      CANDIDATES_HARD_CAP: "2000"
      NPROBE_PRIMARY: "240"
      NPROBE_SECOND_PASS: "240"
      BORDERLINE_SECOND_PASS_ENABLED: "0"
      BORDERLINE_HITS_MIN: "2"
      BORDERLINE_HITS_MAX: "3"
      RINHA_RESOURCES_DIR: /app/resources
      ERL_AFLAGS: "+S 1:1 +A 1 +sbwt none +sbwtdcpu none +sbwtdio none"
    volumes:
      - sock:/run/sock
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: 165MB

volumes:
  sock:
