events {
  worker_connections 2048;
}

http {
  upstream rinha_api {
    server api01:4000 max_fails=3 fail_timeout=1s;
    server api02:4000 max_fails=3 fail_timeout=1s;
    keepalive 256;
  }

  server {
    listen 9999;

    location = /ready {
      proxy_http_version 1.1;
      proxy_set_header Connection "";
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_connect_timeout 500ms;
      proxy_send_timeout 2100ms;
      proxy_read_timeout 2100ms;
      proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
      proxy_next_upstream_tries 2;
      proxy_pass http://rinha_api;
    }

    location = /fraud-score {
      proxy_http_version 1.1;
      proxy_set_header Connection "";
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_connect_timeout 500ms;
      proxy_send_timeout 2100ms;
      proxy_read_timeout 2100ms;
      proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
      proxy_next_upstream_tries 2;
      proxy_pass http://rinha_api;
    }

    location / {
      return 404;
    }
  }
}
